### ISSUE TITLE
Installation documentation is missing dependency.

### ISSUE THREAD

**Issue by Metsuryu** [flarum/flarum.github.io#70] opened 2018-05-08 10:12 UTC
http://flarum.org/docs/installation/

Under "System Requirements" it says:

> PHP 5.6 up to 7.1 (not 7.2) with the following extensions: mbstring, pdo_mysql, openssl, json, gd, dom, fileinfo

But it also needs the `curl` extension, at last for php7.0.

**Comment by luceos** [comment] 2018-05-08 10:25
@Metsuryu is curl not a requirement of composer?

**Comment by Metsuryu** [comment] 2018-05-08 10:31
@luceos It was required to install flarum with `composer install`, I think. I had no idea, since I never used composer, so I had to search for a solution for a while. I think it's worth writing it in the docs somewhere at least.

**Comment by franzliedke** [comment] 2018-05-17 12:34
Didn't this come up recently? It's a Composer requirement, not one of Flarum, strictly speaking. (That might change when we integrate more closely with Composer.)

**Comment by franzliedke** [comment] 2018-05-17 12:40
Ah, I knew it. Closing this as a duplicate of #69. Akismet is the culprit.

**Closed as completed by franzliedke** 2018-05-17 12:40 UTC

**Comment by franzliedke** [comment] 2018-05-17 13:33
For the record: We now [unbundled the Akismet extension](https://github.com/flarum/flarum/commit/088fdb41109d39194903ec91458c4b6353a8179d).
